name: Latest Release

on:
  push:
    tags:
      - "v*"

defaults:
  run:
    shell: bash

jobs:
  lint:
    name: Lint files
    runs-on: "ubuntu-latest"
    steps:
      - uses: actions/checkout@v2.3.4
      - uses: actions/setup-go@v2
        with:
          go-version: 1.16
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v2.5.2
        with:
          version: latest
          working-directory: api/v1
  test:
    name: Run tests
    runs-on: "ubuntu-latest"
    steps:
      - uses: actions/checkout@v2.3.4

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.16

      - name: Run Go Test
        run: |
          cd api/v1
          go test -v -cover ./...
  build:
    name: Build
    runs-on: 'ubuntu-latest'
    needs: test
    steps:
      - name: Checkout code
        uses: actions/checkout@v2.3.4
      - name: Build with xgo
        uses: crazy-max/ghaction-xgo@v1
        with:
          xgo_version: latest
          go_version: 1.16
          working_dir: api/v1
          dest: build
          prefix: nutrity-api-v1
          targets: linux/386, linux/amd64, windows/386, windows/amd64, darwin/386, darwin/amd64
          v: true
          x: false
          ldflags: -s -w
          buildmode: default
      - name: Archive build artifacts
        uses: actions/upload-artifact@v2
        with:
          name: nutrity-build-artifacts
          path: api/v1/build
  release:
    name: Create Release
    runs-on: 'ubuntu-latest'
    needs: build
    steps:
      - name: Checkout code
        uses: actions/checkout@v2.3.4
      - name: Download build artifacts
        uses: actions/download-artifact@v2
        with:
          name: nutrity-build-artifacts
      - name: Release Notes
        run:
          git log $(git describe HEAD~ --tags --abbrev=0)..HEAD --pretty='format:* %h %s%n  * %an <%ae>' --no-merges >> ".github/RELEASE-TEMPLATE.md"
      - name: Release with Notes
        uses: softprops/action-gh-release@v1
        with:
          body_path: ".github/RELEASE-TEMPLATE.md"
          draft: true
          files: build
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
